### ISSUE TITLE
Update campus.openhatch.org

### ISSUE THREAD

**Issue by shaunagm** [openhatch/open-source-comes-to-campus#114]
- [x] "What we provide" should be shorter, less detailed, no links)
- [x] Getting started should be higher and more prominent on the page and should link to Discourse, not to hello@
- [x] "Upcoming Events" -  link prominently to events.openhatch.org so people can find local events (and so we show we have active events)
- [x] "Past events" - link to events.openhatch.org and maybe also the blog
- [x] rethink "How to help out" section
- [ ] remove link to event website on the "getting involved" page
- [ ] shrink down "past events" to take 1/2 or 1/3 of the space (maybe turn events into a simple list, with images in the side columns?)
- [ ] add brief intro section before going into "what we provide"
- [ ] reconfigure buttons to, in order: "Learn More" (contains intro, and what we provide), "Getting Involved" (contains proposing an event and other ways to participate); "Events" (contains upcoming events and past events, with the upcoming events texts very large); "sponsors" -- each section has a different background color to distinguish

**Comment by shaunagm** [comment]
@dcwalk @paulproteus @willingc - can you think of new folks who could test out this new flow?

**Comment by dcwalk** [comment]
@shaunagm I should be able to get someone to look at this before the weekend!

**Comment by shaunagm** [comment]
That'd be swell, @dcwalk :)

**Comment by dcwalk** [comment]
Okay, so I observed a run through and got the following comments (some a little more meta and maybe touching on oh-mainline... including...: openhatch/oh-mainline#1602), let me know your thoughts on if this is worth pursuing in the oh-mainline repo:
- When landing on openhatch.org and trying to figure out next steps for an event, the expectation was that the upper left hand events (https://openhatch.org/events/) would point to upcoming events, as the content seems similar to that on the front page
- On the openhatch.org front page there was some confusion on what affiliated versus open source comes to campus meant (as in, as an organizer who wanted to bring an event to campus, which to click?)

That aside, looking at the **campus documentation** itself the comments were:
- Overall comment: seems like a bunch of different services that don't feel integrated together
- Wanted more information on one single page instead of discourse and the wiki. Felt the wiki was more difficult to read (admitted this was personal preference)
- Thought the amount of space for things that weren't as important could be emphasized (e.g. past event section is large, maybe smaller images or more condensed spacing?)
- An issue with the images, they appear to align left in chrome on linux leaving white space on the right side 
- Would be nice to have events split off from past events in the top buttons, also a button for each category (including sponsors)
- Confusing to have the first link off the page go to the events.openhatch.org site, which is brand new at this point (assuming they've landed from the main site)
- Thought the "If you're looking to participate, ..." under Upcoming events was odd placement

Finally, some comments from the events.openhatch.org site:
- Is there some way to have all the types of potential events listed on the main site represented there for consistency sake? (right now: "Do you want to learn about open source with fun and friendly people? Sign up and RSVP for an event. You can also check out your local chapter. Or, learn more about OpenHatch Events."
- The 'learn more about OpenHatch events' points to a page on the railsbridge app and that caused confusing (https://events.openhatch.org/about), especially as there is a different 'about' page from the main openhatch site (https://openhatch.org/about/) that redirects to the wiki
- Confusion over events.openhatch.org and openhatch.org/events being different

So I'm leaving these all together but really the comments could (maybe should) be in a few different issues. Let me know how you want to proceed.

I could attempt a mockup tomorrow if you would like.

**Comment by shaunagm** [comment]
re: campus.openhatch.org suggestions - these largely make sense.  
- Perhaps we could have a bit more explanation of what OSCTC _is_ before jumping in to "what we provide".
- Past events section could definitely shrink down to about half that size - the current format was chosen 30+ events ago, when it didn't take up such a high % of the page.  This would also fix the images issue hopefully.

re: the openhatch mainline alterations - it's probably worth filing an issue, but it might make sense to wait until we know that campus.openhatch.org and events.openhatch.org look like before deciding what the /events page will say and where it will point to.

re: events.openhatch.org: we could definitely expand it to cover different kinds of events.  Unfortunately, the RailsBridge app is not super freeform - to add a particular kind of event you need to at least edit a template file, and I think also a bit of ruby code.  But I can add known types of workshop, including the ones currently on the OH about page, like Python Workshop for Women & Friends, as well as a few others - short events, online events, etc, and the about page could be updated to provide more details about these events.

**Comment by dcwalk** [comment]
Cool, what would be the next steps here? I'm just about to update #118, seems like these issues need to be tackled/resolved in sync.

**Comment by shaunagm** [comment]
I've updated the checklist above - please feel free to address the added issues, if not I will get to them myself sometime soon.  

What were you thinking of mocking up?  campus.openhatch.org?
