### ISSUE TITLE
Create discourse to wiki flows of canonical info

### ISSUE THREAD

**Issue by shaunagm** [openhatch/open-source-comes-to-campus#118]
We envision the organizer flow to be from events.openhatch.org to discourse to the wiki.  
- [x] Modify community to be clearly not OSCTC-specific, and more about creating space for interest groups to chat.
- [x] Move mentor and volunteer facing threads, including template threads, to logistics.
- [x] Rename logistics to "[Event Help](http://discourse.openhatch.org/c/event-help)" (getting help for your event) 
- [ ] Streamline the info on Discourse - only high level stuff should be there, the rest should point to wiki with a few exceptions.

**Comment by dcwalk** [comment]
I'm going to tackle this issue first, ping me if I wind up as a blocker!

**Comment by paulproteus** [comment]
This is super super duper exciting.​

**Comment by codersquid** [comment]
:) :+1: because I was hoping to use the discussion area for things like Community Data Science Workshop too.

**Comment by shaunagm** [comment]
Cool, @codersquid!

**Comment by dcwalk** [comment]
@shaunagm I can't actually modify the name of the category, that might have to be you?

**Comment by shaunagm** [comment]
Done!

**Comment by dcwalk** [comment]
Cool @shaunagm, looks good. Do you still think it would be valuable to remove the topics within [event help](http://discourse.openhatch.org/c/event-help) or leave them for now?

Also, can you move the [Volunteers & Mentors](http://discourse.openhatch.org/c/community/volunteers-mentors) topic to the Contribute category? 

I think that would take care of one of the other points above! I adjusted the descriptions already.

**Comment by shaunagm** [comment]
I think it's probably fine to leave them there, at least until we have a better idea.

And I've moved the Volunteers & Mentors subcategory.

**Comment by dcwalk** [comment]
An update on this, I think the balance right now is okay... but discourse should be updated in concert with #114. Further, will need to adjust/update the wiki content, haven't begun to tackle that, will add some tools here.

Tools for looking at wiki pages:
[General Statistics](https://openhatch.org/wiki/Special:Statistics)
[Listing of all Pages](https://openhatch.org/w/index.php?title=Special%3AAllPages&from=1&to=&namespace=0) -- have to select 1 of 4 slices, ~300 per section
[Orphaned Pages](https://openhatch.org/w/index.php?title=Special:LonelyPages&limit=500&offset=0)
[Categories](https://openhatch.org/w/index.php?title=Special:Categories) -- OSCTC category only has 2 pages. A good first step might be adding relevant pages to the category. 
[Unused Categories](https://openhatch.org/wiki/Special:UnusedCategories) -- Pages to Delete/Out of Date categories exist but are unused, might be great resource for updating content.
['Special' Pages available on OpenHatch for diagnosing wiki](https://openhatch.org/w/index.php?title=Special:SpecialPages)
['Special' Pages complete listing](https://en.wikipedia.org/wiki/Help:Special_page#General_information)

Thoughts on next step?

**Comment by shaunagm** [comment]
I think it might be time to start brainstorming use cases and thinking about what their "flows" would be onto the site.  Types of users we might want to make use cases for:
- people interested in learning more about organizing events
- people who have decided to organize an event
- people who are mentoring at an event
- people attending an event as students
- people wanted to run affiliated events
- people who want to welcome newcomers to their projects via events
- people who want to contribute to OSCTC
